name: CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install proselint
      - run: proselint _posts/2022-09-21-auto-build-gcp-custom-image-with-cloudbuild-and-packer.md
